version: "3.8"
services:
  rtmp:
    image: tiangolo/nginx-rtmp:latest
    container_name: rtmp
    platform: linux/amd64       # keep on Apple Silicon
    ports:
      - "1935:1935"             # RTMP ingest
      - "8000:8080"             # HTTP out (image serves HTTP on 8080)
    volumes:
      - ./nginx-rtmp.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
